services:
  - docker:dind

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build -t registry.gitlab.com/jonny990421-studium/vv/elklogger/elkdemo:latest .
    - docker push registry.gitlab.com/jonny990421-studium/vv/elklogger/elkdemo:latest
    
