filebeat.inputs:
  - type: filestream
    enabled: true
    paths:
      - ${LOG_PATH}/*.json
    json.keys_under_root: true
    json.message_key: message
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

processors:
  - timestamp:
      field: json.timeMillis
      layouts:
        - UNIX_MS
        - UNIX
      test:
        - 1589117576765

output.elasticsearch:
  enabled: true
  hosts: '${ELASTICSEARCH_HOSTS}'
  indices:
    - index: "filebeat-%{+yyyy.MM.dd}"

